version: '3.8'

services:
  env-check:
    image: busybox
    env_file:
      - ../../.env
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    command: >
      sh -c "echo 'Checking Database Environment Variables:' &&
             echo 'DATABASE_URL=' $$DATABASE_URL &&
             echo 'POSTGRES_USER=' $$POSTGRES_USER &&
             echo 'POSTGRES_DB=' $$POSTGRES_DB &&
             echo 'POSTGRES_PASSWORD exists=' $${POSTGRES_PASSWORD:+true}"

  url-service:
    env_file:
        - ../../.env
    build:
      context: ../../services/url-service
      dockerfile: Dockerfile
    ports:
      - "${URL_SERVICE_PORT:-3001}:3000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_URL=${REDIS_URL}
    volumes:
      - ../../services/url-service:/app
      - /app/node_modules
    depends_on:
      - postgres
      - redis

  redirect-service:
    env_file:
      - ../../.env
    build:
      context: ../../services/redirect-service
      dockerfile: Dockerfile
    ports:
      - "${REDIRECT_SERVICE_PORT:-3002}:3000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_URL=${REDIS_URL}
    volumes:
      - ../../services/redirect-service:/app
      - /app/node_modules
    depends_on:
      - postgres
      - redis

  analytics-service:
    env_file:
      - ../../.env
    build:
      context: ../../services/analytics-service
      dockerfile: Dockerfile
    ports:
      - "${ANALYTICS_SERVICE_PORT:-3003}:3000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_URL=${REDIS_URL}
    volumes:
      - ../../services/analytics-service:/app
      - /app/node_modules
    depends_on:
      - postgres
      - redis

  auth-service:
    env_file:
      - ../../.env
    build:
      context: ../../services/auth-service
      dockerfile: Dockerfile
    ports:
      - "${AUTH_SERVICE_PORT:-3004}:3000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_URL=${REDIS_URL}
    volumes:
      - ../../services/auth-service:/app
      - /app/node_modules
    depends_on:
      - postgres
      - redis

  postgres:
    env_file:
      - ../../.env
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_EXTERNAL_PORT:-5433}:5432"

  redis:
    env_file:
      - ../../.env
    image: redis:alpine
    ports:
      - "${REDIS_PORT:-6379}:6379"

volumes:
  pgdata: